app = "nostra-dataload"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  image = "mcr.microsoft.com/mssql/server:2022-latest"

[env]
  ACCEPT_EULA = "Y"
  MSSQL_PID = "Developer"

[mounts]
  source = "nostra_sqlserver_data"
  destination = "/var/opt/mssql"

[http_service]
  internal_port = 1433
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024